name: Test Workflow
run-name: ${{ github.actor }} launched the Test workflow 🚀

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "*"

  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  test_gh_fetch_workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # - name: Check env vars
      #   run: |
      #     # echo "GITHUB_SHA=\"${{ github.sha }}\"" >> .env.prod
      #     # echo "GITHUB_REF=\"${{ github.ref }}\"" >> .env.prod
      #     # echo "GITHUB_REF_NAME=\"${{ github.ref_name }}\"" >> .env.prod
      #     # echo "GITHUB_REF_TYPE=\"${{ github.ref_type }}\"" >> .env.prod
      #     # echo "GITHUB_REF_NAME=\"${{ github.ref_name }}\"" >> .env.prod

      - name: Run deploy script
        run: |
          echo "Running deploy script"
          pnpm install
          pnpm run run:deploy

      - name: Send Debug Log to API
        uses: actions/github-script@v6
        with:
          script: |
            // Send POST request to API

            const data = { github_sha: '${{ github.sha }}', github_ref: '${{ github.ref }}', github_ref_name: '${{ github.ref_name }}', github_ref_type: '${{ github.ref_type }}', github_ref_name: '${{ github.ref_name }}' }

            const response = await fetch('https://dev3k.yespranav.com/api/v1/test', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(data)
            });
